### ISSUE TITLE
Help!  Don't know how to do this

### ISSUE THREAD

**Issue by Tylersuard** [huaxiaozhong1/complete-procedure-to-train-and-recognize-you-by-raspberry-pi-3-and-tensorflow-lite#1]
Hello.  I'm having a hard time following any of these instructions, and I can't get Docker to with your commands.  Is there any way you would have a pre-made image of Raspbian Buster with tensorflow lite already on it?  Thank you!

**Comment by huaxiaozhong1** [comment]
Sorry for the late response. I am on vacation now until August 20th.But I may have time to help you. First of all, have you successfully run Ubuntu 18.04 docker container?

**Comment by huaxiaozhong1** [comment]
Hello, if your don't have further question around this issue, could you close the issue? Thanks,
